version: "2"

services:
  rng:
    image: dockercoins/rng:v0.1

  hasher:
    image: dockercoins/hasher:v0.1

  webui:
    image: dockercoins/webui:v0.1
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    image: dockercoins/worker:v0.1

